### ISSUE TITLE
Registration & Login - java.lang.NoSuchMethodError: XMPPServer.getIQAuthHandler()

### ISSUE THREAD

**Issue by BrianJVarley** [oskapt/docker-openfire#3]
I did a `docker build` off tag `image: monachus/openfire:latest`and spun up the image with docker-compose.

So far the image is working fine when connecting via XMPP clients and sending messages.

But when I try to access the `Registration & Login` section on the Admin Console, I get the error:

`java.lang.NoSuchMethodError: org.jivesoftware.openfire.XMPPServer.getIQAuthHandler()Lorg/jivesoftware/openfire/handler/IQAuthHandler;
`

When I followed the build steps here  - https://github.com/oskapt/docker-openfire#building-the-container I didn't see any error regarding the `QAuthHandler`.

Also looking at the JavaDocs for Openfire there is no `getIQAuthHandler` method that I can see in the `http://download.igniterealtime.org/openfire/docs/latest/documentation/javadoc/org/jivesoftware/openfire/XMPPServer.html` module.

Did you notice the same on any of your builds? 
Looking at the issues there isn't a similar issue raised for this exception. It seems that the link it the admin console is calling `XMPPServer.getIQAuthHandler()` 

**Complete exception log:**
```
Exception:
java.lang.NoSuchMethodError: org.jivesoftware.openfire.XMPPServer.getIQAuthHandler()Lorg/jivesoftware/openfire/handler/IQAuthHandler;
	at org.jivesoftware.openfire.admin.reg_002dsettings_jsp._jspService(reg_002dsettings_jsp.java:96)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:118)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:76)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:165)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by oskapt** [comment]
I haven't seen this before, but I no longer run Openfire. I run Mattermost, and I should probably pull down the openfire repo on Github and Docker Hub...

Similar issue here: https://igniterealtime.jiveon.com/thread/61151 <https://igniterealtime.jiveon.com/thread/61151>

Doc is here: http://web.mit.edu/ghudson/dev/openfire/documentation/docs/javadoc/org/jivesoftware/openfire/XMPPServer.html <http://web.mit.edu/ghudson/dev/openfire/documentation/docs/javadoc/org/jivesoftware/openfire/XMPPServer.html>, and it looks like this is something in the 3.3.0 code.

I'll try to kick off a build in the near future and see if I hit the same issue.

**Comment by BrianJVarley** [comment]
Hi @oskapt, I tried upgrading the `ENV OF_VERSION 4.2.2` in Dockerfile to latest build 4.2.2, then re-running a `docker build`. But the same error is thrown accessing `Registration & Login` in Admin console when image is composed. So it seems to be any later images than 3.3.0 that are having this exception.

Sure I see that the `3.3.0` version of Openfire contains the missing `getIQAuthHandler()` method but I don't want to revert my Openfire image that far back. Let me know what happens with the build and if you see the same, thanks
